### ISSUE TITLE
Allow the use of HTTP Proxy

### ISSUE THREAD

**Issue by gbossert** [SEKOIA-IO/SEKOIA.IO-for-Splunk#5]
I would like to configure SEKOIA.IO-for-Splunk to connect on the API of SEKOIA.IO by means of my web proxy.

Current environment:
* Splunk 8.0.5
* Python 3

I don't need to specify authentication parameters, only a hostname and a port.

**Comment by gaelmuller** [comment]
This was added in v1.0.3
